services:
  nginx:
    image: docker.io/library/nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
    restart: always




# Update nginx to play recorder


  rosblox-studio:
    image: ghcr.io/rosblox/studio:latest
    volumes:
      - ./studio/layout.json:/src/layout.json
      - ./studio/layout.json:/foxglove/default-layout.json
    ports:
      - 8080:8080
    restart: always

  ros-foxglove-bridge:
    image: ghcr.io/rosblox/ros-foxglove-bridge:humble
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    command: su - ros --whitelist-environment="ROS_DOMAIN_ID" /run.sh

  ros-livox-ros-driver2:
    image: ghcr.io/rosblox/ros-livox-ros-driver2:humble
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    volumes:
      - ./livox_ros_driver2/MID360_config.json:/colcon_ws/src/livox_ros_driver2/config/MID360_config.json
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    command: su - ros --whitelist-environment="ROS_DOMAIN_ID" /run.sh


  ros-bag-recorder:
    image: ghcr.io/rosblox/ros-bag-recorder:humble
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    working_dir: /bags    
    volumes:
      - ~/bags:/bags
      - ./ros-bag-recorder/qos_override.yaml:/qos_override.yaml
    command: su - ros --whitelist-environment=ROS_DOMAIN_ID  -c 'source /opt/ros/humble/setup.bash; cd /bags; ros2 bag record --max-cache-size 1000000000 -s mcap  --qos-profile-overrides-path /qos_override.yaml  --max-bag-size 100000000 /livox/lidar /livox/imu'
